#!/usr/bin/env python3
""" perform a development install of cocotb_kernel

    On Binder, this will run _after_ the environment has been fully created from
    the environment.yml in this directory.

    This script should also run locally on Linux/MacOS/Windows:

        python3 binder/postBuild
"""
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path.cwd()

def _(*args: str, **kwargs: Any) -> None:
    """ Run a command, echoing the args

        fails hard if something goes wrong
    """
    print("\n\t", " ".join(args), "\n")
    return_code = subprocess.call(args, **kwargs)
    if return_code != 0:
        print("\nERROR", return_code, " ".join(args))
        sys.exit(return_code)

# verify the environment is self-consistent before even starting
_(sys.executable, "-m", "pip", "check")

# install the kernel
_(sys.executable, "-m", "flit", "install", "--symlink")
_(sys.executable, "-m", "cocotb_kernel.install", "--user")

# install WaveDromPy
_(sys.executable, "-m", "pip", "install", "wavedrom")

print("\ncocotb kernel has been successfully installed\n")